test:
	gcc veri_disk_write.c -o veri_disk_write
	echo "********please to run veri_disk_write.exe******"

	gcc veri_disk_read.c -o veri_disk_read
	echo "********please to run veri_disk_read.exe******"


all:
	gcc veri_disk_write.c -o veri_disk_write
	echo "********please to run veri_disk_write.exe******"

	gcc veri_disk_read.c -o veri_disk_read
	echo "********please to run veri_disk_read.exe******"




clean:
	del -f *.exe
