
test:
	gcc toy_machine.c toy_compiler.c toy_assembler.c toy_CPU.c misc.c -o toy_machine
	echo "********please run toy_machine.exe******"
# 请在命令行运行 toy_machine.exe
all:
	gcc main.c -o main
	echo "********please run main.exe******"


clean:
	del -f *.exe
