test:
	gcc sizeof.c -o sizeof
	echo "********start to run sizeof.exe******"
	sizeof.exe
	echo "********end to run sizeof.exe******"

all:
	gcc veri_QPC_time.c -o veri_QPC_time
	echo "********start to run veri_QPC_time.exe******"
	veri_QPC_time.exe
	echo "********end to run veri_QPC_time.exe******"

	gcc sizeof.c -o sizeof
	echo "********start to run sizeof.exe******"
	sizeof.exe
	echo "********end to run sizeof.exe******"

clean:
	del -f *.exe
