test:
	gcc main.c -lpthread -o main
	echo "********start to run main.exe******"
	main.exe
	echo "********end to run main.exe******"

all:
	gcc main.c -lpthread -o main
	echo "********start to run main.exe******"
	main.exe
	echo "********end to run main.exe******"


clean:
	del -f *.exe
